version: "3.9"
services:
  dnstap-sensor:
    image: deteque/dnstap-sensor
    volumes:
      - /etc/dnstap/:/etc/dnstap/
  socket-proxy:
    image: deteque/socket-proxy
    volumes:
      - /etc/dnstap/:/etc/dnstap/
    command: ["socket-proxy", "-s", "/etc/dnstap/dnstap.sock", "-d", "/etc/dnstap/dnstap-proxy1.sock", "-d", "/etc/dnstap/dnstap-proxy2.sock"]
  bind:
    image: deteque/bind-rpz
    network_mode: host
    volumes:
      - /etc/dnstap/:/etc/dnstap/
      - /etc/namedb/:/etc/namedb/
